# 项目相关配置
think:
  # 名称
  name: Think
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/think/uploadPath，Linux配置 /home/think/uploadPath）
  profile: /home/uat/wisdomgd/backend/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认240分钟）
    expireTime: 240

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mybatis/system/*Mapper.xml, classpath:/mybatis/business/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/shizhiguan/*

# 代码生成
gen:
  # 作者
  author: LF
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.think.web.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
